#!/usr/bin/python

"""Amulet tests on a basic Cinder deployment on utopic-juno."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='utopic')
    deployment.run_tests()
