#!/usr/bin/python

"""Amulet tests on a basic Cinder git deployment on vivid-kilo."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='vivid', git=True)
    deployment.run_tests()
