#!/usr/bin/python

"""Amulet tests on a basic cinder deployment on precise-folsom."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='precise',
                                         openstack='cloud:precise-folsom',
                                         source='cloud:precise-updates/folsom')
    deployment.run_tests()
