#!/usr/bin/python

"""Amulet tests on a basic cinder deployment on precise-havana."""

from basic_deployment import CinderBasicDeployment

if __name__ == '__main__':
    deployment = CinderBasicDeployment(series='precise',
                                         openstack='cloud:precise-havana',
                                         source='cloud:precise-updates/havana')
    deployment.run_tests()
