###############################################################################
# [ WARNING ]
# Configuration file maintained by Juju
# local changes may be overwritten.
###############################################################################
{% if castellan_enabled %}
[key_manager]
backend = {{ castellan_backend }}

[vault]
vault_url = {{ vault_url }}
kv_mountpoint = {{ secret_backend }}
kv_version = 1

{% endif %}
