###############################################################################
# [ WARNING ]
# Configuration file maintained by Juju
# local changes may be overwritten.
###############################################################################
{% if castellan_enabled %}
[Service]
Environment="OS_VAULT__APPROLE_ROLE_ID={{ role_id }}"
Environment="OS_VAULT__APPROLE_SECRET_ID={{ secret_id }}"

{% endif %}