###############################################################################
# [ WARNING ]
# Configuration file maintained by Juju
# local changes may be overwritten.
###############################################################################
{% if castellan_enabled -%}
{% for sect, pairs in castellan_secret_map_sections.items() -%}
[{{ sect }}]
{% for k, v in pairs -%}
{{ k }} = {{ v }}
{% endfor -%}

{% endfor -%}
{% endif -%}